name: bookhair
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  getwidget: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/menu.png
    - assets/icons/hair.png
    - assets/icons/beard.png
    - assets/icons/eyebrow.png
    - assets/icons/chemistry.png
    - assets/icons/
    - assets/icons/map.png
