name: bookhair
description: "Aplicativo de agendamento de barbearias."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https:
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https:
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  getwidget: ^4.0.0
  http: ^1.4.0
  provider: ^6.0.5
  table_calendar: ^3.0.9
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.10.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/img/logo-dark.png"
  android_adaptive_icon_foreground: "lib/assets/img/logo-dark.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/fonts/
    - lib/assets/img/logo.png
    - lib/assets/img/logo-dark.png
    - assets/icons/menu.png
    - assets/icons/hair.png
    - assets/icons/beard.png
    - assets/icons/eyebrow.png
    - assets/icons/chemistry.png
    - assets/icons/
    - assets/icons/map.png
    - assets/images/barbershop_example.png
    - assets/images/barbershop_2.png

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Poppins-Italic.ttf
          style: italic
